### ISSUE TITLE
How to launch the editor ?

### ISSUE THREAD

**Issue by Jacques-Olivier-Farcy** [dozingcat/Vector-Pinball-Editor#12]
Hi there,

I don't know Java, can you describe how do i launch your editor ?

**Comment by Jacques-Olivier-Farcy** [comment]
Si i have downloaded and installed IntelliJ.
I tried with the community edition :
https://www.jetbrains.com/idea/download/download-thanks.html?platform=windows&code=IIC

After that i opened main.java ...

Well i am a bit lost there

**Comment by dozingcat** [comment]
In IntelliJ you should be able to right-click on Main.java in the project view and select "Run Main.main()" from the menu.

**Comment by Jacques-Olivier-Farcy** [comment]
Can you detail how you open the project ?

**Comment by dozingcat** [comment]
After you clone the repository with git, you should be able to launch IntelliJ and open an existing project. Navigate to the Vector-Pinball-Editor directory and open it. Then Main.java should be under src/com.dozingcatsoftware.vectorpinball and you can run it as described above.

**Comment by Jacques-Olivier-Farcy** [comment]
I've made some progress i think.

But i have this message :

![image](https://user-images.githubusercontent.com/19731340/91860363-dd7f8880-ec6b-11ea-98ee-bf3246d2b6e2.png)

**Comment by dozingcat** [comment]
Java used to include the JavaFX libraries in the standard install, but current versions don't. You'll need to download JavaFX separately and then point the project to it. https://openjfx.io/openjfx-docs/ might help.

Sorry, this is way more annoying than it should be.

**Comment by Jacques-Olivier-Farcy** [comment]
No worry, i could help to write a step by step guide to help people making tables

**Comment by Jacques-Olivier-Farcy** [comment]
But if you have a way to make it simplier, it could really help :)

**Comment by SZRabinowitz** [comment]
if you install java jusr run ./gradlew run or gradlew.bat run

**Comment by dozingcat** [comment]
Now that the build system uses Gradle, IntelliJ should be able to run it without having to manually installing JavaFX. Also as noted above `./gradlew run` or `gradlew.bat run` from the command line should work.
